import {
  IsEmail,
  IsNotEmpty,
  IsString,
  Matches,
  MaxLength,
  MinLength,
} from 'class-validator';

/**
 * Creating a school and the person who will run it.
 *
 * The platform operator chooses the administrator's username; the password is
 * generated by the API so that nobody, including the operator, gets to pick a
 * weak one for somebody else's account.
 */
export class CreateSchoolDto {
  @IsString()
  @IsNotEmpty()
  @MinLength(2)
  @MaxLength(120)
  name!: string;

  @IsString()
  @IsNotEmpty()
  @MaxLength(120)
  adminDisplayName!: string;

  /** The same shape a student's username takes, for the same reason. */
  @IsString()
  @IsNotEmpty()
  @MinLength(3)
  @MaxLength(50)
  @Matches(/^[a-zA-Z0-9._-]+$/, {
    message: 'Username may contain only letters, numbers, dots, dashes and underscores.',
  })
  adminUsername!: string;

  /**
   * Required, unlike a student's. A school administrator has nobody above her
   * inside her school to reset her password, so self-service recovery is her
   * only way back in — the same rule a teacher follows (SRS 28.5).
   */
  @IsEmail()
  @MaxLength(200)
  adminEmail!: string;
}

export class RenameSchoolDto {
  @IsString()
  @IsNotEmpty()
  @MinLength(2)
  @MaxLength(120)
  name!: string;
}
